### ISSUE TITLE
Github action which builds docker image and pushes it into registry after a new tag is introduced

### ISSUE THREAD

**Issue by tschm** [VanekPetr/investment-funnel#124]
@VanekPetr You should get an account on docker hub to publish the images you construct (every time you tag)

**Comment by VanekPetr** [comment]
Hi @tschm, sorry for my late reply.

Right now I am building docker images 'manually'/locally and then pushing it to private Amazon Elastic Container Registry from where I am deploying it to Amazon App Runner (https://investment-funnel.algostrata.com).

I was thinking about 'Build' GitHub action which based on click would build docker image, take credentials from GitHub secrets and push it to Amazon ECR. Then the deployment part for https://investment-funnel.algostrata.com I would still like to keep outside of GitHub.

What do you think about it? Would it make more sense to build automatically based on a new tag? Or have public container registry for it?

**Comment by tschm** [comment]
Yes, build only when a tag is introduced and tag the image with this tag. You could push to a registry you control

**Comment by VanekPetr** [comment]
I was thinking about auto-build of the docker imager after any new release but I believe it would be an overkill right now. 

Currently, we have a new version after each dependency update. Furthermore, not all updates are major... therefore no need to build a new image.

Therefore, I will keep build and deploy as a manual process for now.
