### ISSUE TITLE
Create function/method which combines investment-funnel modules to future-test for different life cycle and risk appetite/preference

### ISSUE THREAD

**Issue by VanekPetr** [VanekPetr/investment-funnel#155]
**Subtasks:**

1. Create a new branch in the Investment Funnel where we are going to collaborate.
2. Estimate covariance matrix based on 10 (or other defined train set) years of historical data. -> (leveraging already created Investment Funnel method)
3. Generate set of x-per-asset-scenarios based on selected years of historical data. -> (leveraging already created Investment Funnel method)
4. Create function which finds y optimal scenarios based on provided y risk levels using the data from above.
5. Create function to do future testing for these y optimal scenarios.

**Comment by tschm** [comment]
I don't understand why you would need 10 years of data to estimate a covariance matrix. This should be done in a moving manner, e.g. as discussed in the paper by Johanson, Boyd et al. Please don't estimate a matrix over an interval and then use it to run portfolio optimization over the same interval. Your results will look amazing but you have a forward looking bias

**Comment by VanekPetr** [comment]
Hi @tschm, thank you for your comment. You are right, that estimating a matrix over an interval and then use it to run portfolio optimization over the same interval would be bad idea. The idea here is different, I just described it poorly. 

The idea is to estimate covariance matrix (in a train-set), then generate scenarios (from test set, out of sample) and "future" test a strategy with a fixed risk level. 

I am going to edit the description :)) and of course discuss it with @mikkelbechmogensen.
