### ISSUE TITLE
How do we avoid systematic bias in the construction of the optimal risk budget allocations?

### ISSUE THREAD

**Issue by mikkelbechmogensen** [VanekPetr/investment-funnel#171]

**Comment by mikkelbechmogensen** [comment]
Should we try to get more data, and then make a sampling/estimating split of the data, where we sample on 70% of the data and estimate parameters on 30% of the data? In order to make it robust we could try to sample on the 30% of the data with the worst performance.

Look into FHS method of generating scenarios with a GARCH volatility model.

**Comment by VanekPetr** [comment]
I don't think we need more data at this point. Let's try/discuss the split on the 10y of data we already have.

**Comment by VanekPetr** [comment]
@mikkelbechmogensen Let's talk with Kourosh about it next week.
